Check the results of the fit

In [1]:
from astropy.table import Table
import numpy as np

# My modules
from vsh_fit import vsh_fit
from pmt_convert import st_to_rotgld, st_to_rotgldquad

In [2]:
test_tab = Table.read("test.csv")

# Transform astropy.Column into np.array and mas -> uas
dra = np.array(test_tab["dra"] * 1e3)
ddec = np.array(test_tab["ddec"] * 1e3)
dra_err = np.array(test_tab["dra_err"] * 1e3)
ddec_err = np.array(test_tab["ddec_err"] * 1e3)
ra = np.array(test_tab["ra"])
dec = np.array(test_tab["dec"])
dra_ddec_cov = np.array(test_tab["dra_ddec_cov"] * 1e6)

In [3]:
pmt, err, cor_mat = vsh_fit(dra, ddec, dra_err, ddec_err, ra, dec, dra_ddec_cov, l_max=1)

pmt1, err1, cor_mat1 = st_to_rotgld(pmt, err, cor_mat)

pmt1, err1, cor_mat1

(array([-32.22542036,  37.21703988,  30.27658599,  25.70240445,
        -32.12059929, -40.79822713]),
 array([4.54000732, 4.34205691, 4.58252532, 4.81269249, 4.53321304,
        4.3168119 ]),
 array([[ 1.        , -0.00745872, -0.02508901,  0.01581301, -0.29735471,
          0.09615023],
        [-0.00745872,  1.        ,  0.00685353,  0.28753324,  0.00466684,
         -0.00370987],
        [-0.02508901,  0.00685353,  1.        , -0.08203864, -0.03746342,
         -0.01383566],
        [ 0.01581301,  0.28753324, -0.08203864,  1.        ,  0.04156129,
         -0.13870722],
        [-0.29735471,  0.00466684, -0.03746342,  0.04156129,  1.        ,
         -0.16387021],
        [ 0.09615023, -0.00370987, -0.01383566, -0.13870722, -0.16387021,
          1.        ]]))

Results from my previous codes

           D1      -32    30
           D2       37    28
           D3       30    30
            
           R1       26    32
           R2      -32    30
           R3      -41    28
           
It seems that the estimates are OK, but the formal uncertainties are not.

In [4]:
pmt, err, cor_mat = vsh_fit(dra, ddec, dra_err, ddec_err, 
                               ra, dec, dra_ddec_cov, l_max=2)

pmt2, err2, cor_mat2 = st_to_rotgldquad(pmt, err, cor_mat)

pmt2, err2

(array([-27.91957535,  48.74109337,  14.24527368,  32.1815365 ,
        -46.97382569, -43.57535603,  37.25084014,  -2.95837627,
          9.18214245, -50.49291433,  41.28721674,   2.00079793,
          1.11102175,  25.83199096,  72.00657847, -11.85504588]),
 array([4.91534304, 4.71108004, 4.94997283, 5.10932304, 4.78591296,
        4.51208235, 2.90686057, 2.88012742, 5.66141076, 6.06058816,
        5.53811358, 3.02971937, 3.06515958, 5.86294055, 5.93017668,
        5.07342176]))

Results from my previous codes

           D1      -28    32
           D2       49    31
           D3       14    32
           R1       32    33
           R2      -47    31
           R3      -44    30
         E22R       37    19
         E22I       -3    19
         E21R        9    37
         E21I      -50    40
          E20       41    36
         M22R        2    20
         M22I        1    20
         M21R       26    38
         M21I       72    39
          M20      -12    33

In [5]:
print("               Rotation [uas]             "
      "               Glide [uas]")
print("     R1            R2            R3        "
      "     G1            G2            G3         ")
print("-----------------------------------------   "
      "-----------------------------------------")
print("{0:4.0f} +/- {6:4.0f} {1:4.0f} +/- {7:4.0f} "
      "{2:4.0f} +/- {8:4.0f} {3:4.0f} +/- {9:4.0f} "
      "{4:4.0f} +/- {10:4.0f} {5:4.0f} +/- {11:4.0f}  ".format(*pmt1, *err1))

               Rotation [uas]                            Glide [uas]
     R1            R2            R3             G1            G2            G3         
-----------------------------------------   -----------------------------------------
 -32 +/-    5   37 +/-    4   30 +/-    5   26 +/-    5  -32 +/-    5  -41 +/-    4  
